# Generated by Django 4.2.9 on 2024-01-30 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('regular_users', 'Can Post, comment and Like'), ('moderator_users', 'Can tag posts as misleading')), 'verbose_name_plural': 'Posts'},
        ),
    ]
