# Generated by Django 4.2.9 on 2024-01-30 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_post_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
