# Generated by Django 4.2.9 on 2024-02-07 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predictedlikes',
            old_name='predicted_likes',
            new_name='likes',
        ),
    ]
