# Generated by Django 4.2.9 on 2024-02-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_rename_predicted_likes_predictedlikes_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predictedlikes',
            options={'verbose_name_plural': 'PredictedLikes'},
        ),
        migrations.AlterField(
            model_name='predictedlikes',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
